/**
 * Los recorridos que cruzan celular y panel, las pruebas de permisos por
 * rol, y el cierre: cómo reportar, qué queda pendiente y el glosario.
 */

export const CIERRE = [
  {
    titulo: 'Recorridos de extremo a extremo',
    entrada:
      'Las pruebas anteriores revisan cada pantalla por separado. Estas siguen una jornada completa: lo que se programa el lunes, se ejecuta el martes en carretera y se entrega al cliente el viernes. Son las que de verdad dicen si el sistema sirve.',
    bloques: [
      {
        tipo: 'prueba',
        id: 'E-01',
        titulo: 'De la programación al parte validado',
        rol: 'Supervisor + Jefe de cuadrilla',
        previo: 'Necesitas la computadora y el celular a la vez. Es más cómodo entre dos personas.',
        pasos: [
          '**(Panel, Supervisor)** Entra a **Programación** y crea una partida para hoy: actividad `Limpieza de cunetas`, tramo `AQP-02`, progresivas 150+000 a 150+500, cuadrilla **Cuadrilla 1**, meta 500.',
          '**(Celular, Jefe de cuadrilla)** Abre la aplicación y entra a **Programación**. Comprueba que la partida está.',
          '**(Celular)** Entra a **Reporte Diario** → **Registrar actividad**, origen **Programación**, elige esa partida y registra un metrado de 500.',
          '**(Celular)** Toma dos fotos de evidencia: una **Antes** y una **Después**.',
          '**(Celular)** Entra a **Sincronización** y pulsa **Sincronizar ahora**. Espera a que la cola quede vacía.',
          '**(Panel, Supervisor)** Entra a **Campo** y abre el parte de hoy de la Cuadrilla 1.',
          '**(Panel)** Revisa el registro y las dos fotos. Pulsa **Validar**.',
          '**(Panel)** Vuelve a **Programación** y busca la partida.',
        ],
        esperado: [
          'La partida aparece en el celular sin tener que hacer nada especial.',
          'Al registrar, el aviso dice que se descontó de la partida programada.',
          'El parte llega al panel con el registro y las dos fotos, selladas y con coordenada.',
          'Al validar, el parte pasa a **Validado**.',
          'La partida en **Programación** muestra el avance: 500 de 500, y su estado cambió.',
          'En **Mi Avance** del celular, el cumplimiento del día refleja ese 100 %.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'E-02',
        titulo: 'Del PCI recibido al levantamiento con evidencia',
        rol: 'Supervisor + Jefe de cuadrilla',
        pasos: [
          '**(Panel, Supervisor)** En **PCIs**, abre un documento y asigna un ítem a la **Cuadrilla 1**.',
          '**(Celular)** Entra a **PCIs** y comprueba que el ítem aparece con su plazo.',
          '**(Celular)** En **Reporte Diario**, registra una actividad con origen **PCI** eligiendo ese ítem.',
          '**(Celular)** Toma las fotos **Antes**, **Durante** y **Después**.',
          '**(Celular)** Vuelve a **PCIs**, abre el ítem y pulsa **¿Dar por levantado?**; escribe la nota y confirma.',
          '**(Celular)** Sincroniza.',
          '**(Panel)** Abre el mismo ítem de PCI.',
          '**(Panel)** Entra a **Documentos → Carpetas → PCI** y baja hasta ese ítem.',
        ],
        esperado: [
          'El ítem aparece en el celular con los días que faltan para vencer.',
          'Las fotos llevan el **código del PCI** impreso en el sello.',
          'En el panel, el ítem figura levantado, con la nota y las tres fotos como sustento.',
          'En el árbol de carpetas, las fotos están bajo `PCI → código → Ítem → fecha → ANTES / DURANTE / DESPUES`.',
          'El contador de PCIs vencidos o críticos del Dashboard baja.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'E-03',
        titulo: 'Del gasto en carretera a la aprobación',
        rol: 'Jefe de cuadrilla + Administrador',
        pasos: [
          '**(Celular)** En **Mi Caja**, anota el saldo. Registra un gasto de `85.00` por `Peaje Camaná` con foto de comprobante.',
          '**(Celular)** Sincroniza.',
          '**(Panel, Administrador)** Entra a **Caja chica** y ubica el gasto.',
          '**(Panel)** Abre el comprobante, revisa y pulsa **Aprobar**.',
          '**(Celular)** Refresca **Mi Caja**.',
          '**(Panel)** Ve a **Reportes** y descarga el informe de **Caja chica** en Excel.',
        ],
        esperado: [
          'El gasto llega al panel con su foto.',
          'Al aprobarlo, el estado cambia en los dos lados.',
          'El saldo baja en 85.00 tanto en el celular como en el panel.',
          'El Excel de caja incluye el movimiento con su número de comprobante.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'E-04',
        titulo: 'De todo el mes al paquete para el cliente',
        rol: 'Administrador',
        pasos: [
          'Entra a **Entregables**.',
          'Pon el periodo del mes pasado completo.',
          'Marca las ocho secciones.',
          'Pulsa **Armar paquete** y espera a que termine.',
          'Abre el ZIP y revisa cada carpeta.',
          'Abre el `INDICE.xlsx`.',
          'Abre uno de los PDF de `02_REPORTES_DIARIOS` y una foto de `04_FOTOGRAFIAS`.',
        ],
        esperado: [
          'El ZIP trae las ocho carpetas numeradas más el índice.',
          '`01_PROGRAMACION` tiene el PDF de la programación del periodo.',
          '`02_REPORTES_DIARIOS` tiene un PDF por cada parte, con nombre que incluye la fecha y la cuadrilla.',
          '`04_FOTOGRAFIAS` tiene una subcarpeta por día.',
          'El `INDICE.xlsx` lista todos los archivos con su carpeta, tipo, fecha y peso.',
          'Los PDF abren y se leen; las fotos conservan su sello.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'E-05',
        titulo: 'La jornada completa de una cuadrilla',
        rol: 'Jefe de cuadrilla',
        previo: 'Esta prueba simula un día entero. Tómate el tiempo necesario y anota cualquier fricción.',
        pasos: [
          'Abre la aplicación como si fueran las 6 de la mañana.',
          'Completa el **ATS de cuadrilla** con dos peligros y una firma.',
          'Registra la **charla del día** con un asistente firmado.',
          'Haz la **revisión del vehículo** con su kilometraje.',
          'Revisa un **equipo de seguridad**.',
          'Entra a **Programación** y mira qué toca hoy.',
          'Registra **dos actividades** ejecutadas, con sus fotos.',
          'Registra un **gasto** de caja.',
          'Pide un **insumo** al almacén.',
          'Revisa **Mi Avance**.',
          'Genera el **PDF del parte** y compártelo.',
          'Entra a **Sincronización** y deja la cola vacía.',
        ],
        esperado: [
          'Todo el recorrido se puede hacer sin salir de la aplicación.',
          'En ningún paso la aplicación se cierra sola ni muestra un error incomprensible.',
          'Al final, **Pendientes** está en cero.',
          'Todo lo registrado aparece en el panel web.',
          'Anota cuánto tardaste: si una cuadrilla no puede hacerlo en menos de 15 minutos, eso es una observación.',
        ],
      },
    ],
  },

  {
    titulo: 'Pruebas de permisos por rol',
    entrada:
      'Que cada quien vea solo lo suyo no es un detalle: es la diferencia entre un sistema que se puede entregar al cliente y uno que no. Estas pruebas se hacen entrando y saliendo con distintas cuentas.',
    bloques: [
      {
        tipo: 'prueba',
        id: 'R-01',
        titulo: 'El Visor (COVINCA) no ve la economía interna',
        rol: 'Visor',
        previo: 'Entra al panel con `visor@sigov.dev`. Esta es la prueba de permisos más importante.',
        pasos: [
          'Recorre todo el menú de la izquierda, apartado por apartado.',
          'Comprueba que **no existe** la entrada **Caja chica**.',
          'Escribe a mano la dirección `https://sigov.vercel.app/caja`.',
          'Entra a **Reportes** y cuenta los informes.',
          'Entra a **Entregables** y cuenta las secciones.',
          'Entra a **Documentos → Carpetas** y cuenta las ramas.',
        ],
        esperado: [
          '**Caja chica** no aparece en el menú.',
          'Al escribir la dirección, el sistema **te devuelve al Dashboard**: no se ve ningún importe de caja.',
          'En **Reportes** no está el informe de **Caja chica**.',
          'En **Entregables** hay **siete** secciones, sin `08_GASTOS`.',
          'En **Carpetas** hay **cuatro** ramas, sin `GASTOS`.',
          'En ninguna pantalla aparece un saldo, un importe de caja ni un gasto.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'R-02',
        titulo: 'El Visor no puede escribir nada',
        rol: 'Visor',
        pasos: [
          'Entra a **Programación** e intenta crear o editar una partida.',
          'Entra a **PCIs** e intenta crear un PCI.',
          'Entra a **Campo**, abre un parte e intenta validarlo.',
          'Entra a **Inventario** e intenta editar un elemento.',
        ],
        esperado: [
          'En ningún caso hay botones de crear, editar, eliminar o validar; o si los hay, no hacen nada y el sistema rechaza el cambio.',
          'No se altera ningún dato. Compruébalo volviendo a entrar como Supervisor.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'R-03',
        titulo: 'La auditoría es solo del Administrador',
        rol: 'Varios',
        pasos: [
          'Entra con `supervisor@sigov.dev` y busca **Auditoría** en el menú.',
          'Escribe la dirección `https://sigov.vercel.app/auditoria`.',
          'Repite con `ssoma@sigov.dev`.',
          'Repite con `visor@sigov.dev`.',
          'Repite con `cuadrilla1@sigov.dev`.',
          'Por último entra con `admin@sigov.dev`.',
        ],
        esperado: [
          'Los cuatro primeros no ven la entrada en el menú, y al escribir la dirección el sistema los devuelve al Dashboard.',
          'Solo el Administrador ve la bitácora con contenido.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'R-04',
        titulo: 'El Jefe de cuadrilla solo ve su cuadrilla',
        rol: 'Jefe de cuadrilla',
        previo: 'Entra al panel web con `cuadrilla1@sigov.dev`.',
        pasos: [
          'Entra a **Reporte Diario** y mira de qué cuadrillas son los partes.',
          'Entra a **Fotos / Evidencias** y mira de quién son las fotos.',
          'Entra a **Registro de Gastos / Mi Caja** y mira de qué cuadrilla es el saldo.',
          'Entra a **PCIs** y mira qué ítems aparecen.',
        ],
        esperado: [
          'Todo lo que se ve es de la **Cuadrilla 1 · Calzada y Drenaje**.',
          'No hay ni un solo dato de las cuadrillas 2, 3 o 4.',
          'En el menú no aparecen **Alertas**, **Mapa**, **Inventario**, **SSOMA**, **Auditoría**, **Reportes**, **Formatos**, **Entregables**, **Documentos**, **Importación** ni **Configuración**.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'R-05',
        titulo: 'Nadie cruza de un contrato a otro',
        rol: 'Jefe de cuadrilla (otro contrato)',
        previo: 'Entra con `cuadrilla4@sigov.dev`, que pertenece al contrato **Conservación Huaura – Sayán**, no al de Arequipa.',
        pasos: [
          'Entra al panel web con esa cuenta.',
          'Mira qué contrato aparece arriba a la izquierda.',
          'Recorre **Programación**, **PCIs** y **Reporte Diario**.',
        ],
        esperado: [
          'El contrato que se muestra es **Conservación Huaura – Sayán**.',
          'No aparece ningún dato del contrato de Arequipa – Moquegua – Tacna: ni tramos, ni cuadrillas, ni PCIs, ni partes.',
          'Los tramos que se ven son Huaura – Sayán y Sayán – Churín.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'R-06',
        titulo: 'Cada rol ve el menú que le toca',
        rol: 'Varios',
        previo: 'Ten a mano la tabla de menús del capítulo 3.',
        pasos: [
          'Entra con cada una de las cinco cuentas, una por una.',
          'Anota qué entradas de menú ves en cada caso.',
          'Compara con la tabla del capítulo 3.',
        ],
        esperado: [
          'Cada rol ve exactamente las entradas que dice la tabla, ni una más ni una menos.',
          'Los apartados que cambian de nombre lo hacen: el Administrador ve «Reportes Diarios», el Jefe de cuadrilla «Reporte Diario» y el Visor «Ejecución / Campo».',
        ],
      },
    ],
  },

  {
    titulo: 'Pruebas de aspecto y comportamiento general',
    entrada:
      'Cosas que no pertenecen a un módulo concreto pero que se notan en todo el sistema.',
    bloques: [
      {
        tipo: 'prueba',
        id: 'G-01',
        titulo: 'La identidad de marca es la correcta',
        rol: 'Cualquiera',
        pasos: [
          'Entra al panel y mira la cabecera superior.',
          'Mira el menú de la izquierda.',
          'Mira el pie de la pantalla.',
          'Abre la aplicación del celular y mira la banda de arriba.',
        ],
        esperado: [
          'El logotipo de **Grupo Servicon V&D EIRL** aparece arriba a la izquierda.',
          'Junto a él se lee **SIGOV** con la **V** en verde.',
          'A la derecha está la banda de campaña: «SEGURIDAD EN MOVIMIENTO, COMPROMISO EN CADA KM».',
          'El menú lateral es azul oscuro de la marca, no gris.',
          'Abajo aparece «TRABAJANDO POR VÍAS MÁS SEGURAS».',
          'En el celular se ve la misma banda de marca.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'G-02',
        titulo: 'El panel funciona en el celular',
        rol: 'Cualquiera',
        pasos: [
          'Abre `https://sigov.vercel.app` desde el navegador del celular.',
          'Entra con cualquier cuenta.',
          'Recorre cuatro o cinco apartados.',
        ],
        esperado: [
          'El menú lateral se convierte en un menú que se abre y cierra.',
          'Las tablas se pueden desplazar de lado sin romper la pantalla.',
          'Ningún texto se sale de la pantalla ni queda cortado.',
          'Los botones son lo bastante grandes para pulsarlos con el dedo.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'G-03',
        titulo: 'El modo oscuro',
        rol: 'Cualquiera',
        pasos: [
          'En el panel, pulsa el icono de la luna, arriba a la derecha.',
          'Recorre cinco apartados distintos.',
          'Vuelve al modo claro.',
        ],
        esperado: [
          'Todo el sistema cambia a fondo oscuro.',
          'Los textos se siguen leyendo: nada queda gris sobre gris ni blanco sobre blanco.',
          'Los gráficos y el mapa siguen siendo legibles.',
          'Al volver al modo claro, todo regresa a la normalidad.',
        ],
      },
      {
        tipo: 'prueba',
        id: 'G-04',
        titulo: 'Las esperas se explican',
        rol: 'Cualquiera',
        pasos: [
          'Recarga el panel con F5 y observa el primer segundo.',
          'Entra a un apartado con muchos datos, como **PCIs** o **Inventario**.',
        ],
        esperado: [
          'Al recargar aparece la pantalla de carga con el **logotipo girando** y un texto que dice qué está haciendo.',
          'Dentro de cada apartado, mientras carga se ven bloques grises animados con la forma del contenido, no una pantalla vacía.',
          'Ninguna pantalla se queda cargando para siempre: si algo falla, lo dice.',
        ],
      },
    ],
  },

  {
    titulo: 'Cómo entregar el resultado de las pruebas',
    entrada:
      'Terminadas las pruebas, lo que queda es ordenar lo encontrado para que se pueda corregir.',
    bloques: [
      { tipo: 'subtitulo', titulo: 'La planilla de resultados' },
      { tipo: 'parrafo', texto: 'Copia esta tabla en un Excel o llénala a mano. Una fila por cada prueba de la guía:' },
      {
        tipo: 'tabla',
        columnas: ['Prueba', 'Quién probó', 'Fecha', 'Resultado', 'Observación', 'Captura'],
        filas: [
          ['P-01', '', '', 'Conforme / Con observación / No se pudo', '', 'Sí / No'],
          ['P-02', '', '', '', '', ''],
          ['…', '', '', '', '', ''],
          ['E-05', '', '', '', '', ''],
          ['R-06', '', '', '', '', ''],
        ],
      },
      { tipo: 'subtitulo', titulo: 'Cómo priorizar lo encontrado' },
      {
        tipo: 'tabla',
        columnas: ['Gravedad', 'Qué es', 'Ejemplo'],
        filas: [
          ['**Bloqueante**', 'Impide trabajar o se pierde información.', 'Un registro hecho sin señal no llega al panel; la aplicación se cierra sola al tomar una foto.'],
          ['**Grave**', 'Alguien ve lo que no debe, o un dato sale equivocado.', 'El Visor de COVINCA ve un saldo de caja; un metrado se muestra con la unidad de otra actividad.'],
          ['**Moderada**', 'Funciona pero cuesta usarlo o confunde.', 'Un aviso que no explica qué hacer; un filtro que no se entiende.'],
          ['**Menor**', 'Detalle de presentación.', 'Un texto cortado, un color que no corresponde a la marca, una tilde faltante.'],
        ],
      },
      {
        tipo: 'ojo',
        titulo: 'Reporta de inmediato',
        texto: 'Si encuentras algo **bloqueante** o **grave**, no esperes a terminar toda la guía: avísalo en el momento. Son las dos categorías que pueden obligar a detener una entrega.',
      },
      { tipo: 'subtitulo', titulo: 'Qué queda pendiente de Servicon' },
      { tipo: 'parrafo', texto: 'Hay datos reales del contrato que el sistema todavía no tiene y que hoy muestra vacíos o aproximados. No son fallas del sistema: son información que falta entregar. Conviene tenerlos presentes para no reportarlos como error:' },
      {
        tipo: 'tabla',
        columnas: ['Dato pendiente', 'Dónde se nota', 'Quién lo entrega'],
        filas: [
          ['**RUC y datos fiscales** de Grupo Servicon V&D EIRL', 'El pie de los PDF y de los formatos oficiales.', 'Servicon'],
          ['**Número real del contrato** con COVINCA', 'La cabecera de todos los informes: hoy sale «—».', 'Servicon'],
          ['**Progresivas oficiales** de los cuatro tramos', 'El mapa y la validación de progresivas. Hoy las trazas son aproximadas.', 'Servicon'],
          ['**Fotografía de carretera** para la banda de marca', 'La banda superior del sistema.', 'Servicon'],
        ],
      },
      { tipo: 'subtitulo', titulo: 'Glosario' },
      {
        tipo: 'tabla',
        columnas: ['Término', 'Qué significa'],
        filas: [
          ['**PCI**', 'Pedido de Corrección de Incumplimiento. El documento con el que OSITRAN observa algo y da un plazo para corregirlo.'],
          ['**OSITRAN**', 'El organismo regulador de la infraestructura de transporte de uso público.'],
          ['**COVINCA**', 'El cliente: la concesionaria a la que Servicon presta el servicio de conservación vial.'],
          ['**Progresiva**', 'La ubicación a lo largo de la carretera, en kilómetros y metros. `18+400` es el kilómetro 18 más 400 metros.'],
          ['**Tramo**', 'Un segmento de carretera del contrato, con su progresiva inicial y final.'],
          ['**Metrado**', 'La cantidad ejecutada de una actividad, en su unidad: metros, metros cuadrados, unidades.'],
          ['**Partida**', 'Una actividad programada para una cuadrilla, un tramo y una fecha.'],
          ['**Parte diario**', 'El documento de un día y una cuadrilla, con todo lo que ejecutó.'],
          ['**ATS / IPERC**', 'Análisis de Trabajo Seguro / Identificación de Peligros, Evaluación de Riesgos y Controles.'],
          ['**SSOMA**', 'Seguridad, Salud Ocupacional y Medio Ambiente.'],
          ['**Levantar un PCI**', 'Corregir lo observado y registrar la evidencia que lo demuestra.'],
          ['**Sellar una foto**', 'Imprimir dentro de la imagen la fecha, hora, coordenada y demás datos, de modo que no se puedan separar de ella.'],
        ],
      },
    ],
  },
]
